name: Create a Planetscale branch
on:
  pull_request:
    types: [opened]
    paths:
      - '**.prisma'

jobs:
  create_a_branch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Create a branch
        uses: planetscale/create-branch-action@v1
        id: create_branch
        with:
          org_name: ${{vars.PLANETSCALE_ORGANISATION}}
          database_name: ${{github.event.repository.name}}
          branch_name: ${{ github.head_ref || github.ref_name }} 
          from: main
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}