name: Deploy a deploy request
on:
  pull_request:
    types: [closed]


jobs:
  deploy_deploy_request:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Deploy a deploy request
        uses: planetscale/deploy-deploy-request-action@v3
        with:
          org_name: ${{vars.PLANETSCALE_ORGANISATION}}
          database_name: ${{github.event.repository.name}}
          number: ${{env.CURRENT_DEPLOY_REQUEST_NUMBER}}
          wait: true
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}