name: Terraform Plan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'

jobs:
  plan-terraform:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      
      - name: Initialize Terraform
        run: terraform init
      
      - name: Terraform plan
        id: plan
        run: | 
          terraform plan \
            -out=tfplan \
            -var="vercel_api_token=${{secrets.VERCEL_TERRAFORM_API_TOKEN}}" \
            -var="vercel_protected_deployment_password=${{secrets.VERCEL_PROTECTED_DEPLOYMENT_PASSWORD}}" \
            -var="github_repository_name=${{github.event.repository.name}}" \
            -input=false \
            -no-color

      - name: Upload Terraform plan artifact
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan-${{ github.sha }}
          path: terraform/tfplan
          retention-days: 30

      - name: Post Plan to GitHub PR
        uses: mshick/add-pr-comment@v1
        with:
          allow-repeats: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            ## Terraform Plan
            ```
            ${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}
            ```        