name: Terraform Plan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'

jobs:
  plan-terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      
      - name: Initialize Terraform
        run: terraform init
      
      - name: Terraform plan
        run: | 
          terraform plan \
            -out=tfplan \
            -var="vercel_api_token=${{secrets.VERCEL_TERRAFORM_API_TOKEN}}" \
            -var="vercel_protected_deployment_password=${{secrets.VERCEL_PROTECTED_DEPLOYMENT_PASSWORD}}" \
            -var="github_repository_name=${{github.event.repository.name}}"

      - name: Upload Terraform plan artifact
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan-${{ github.sha }}
          path: terraform/tfplan
          retention-days: 30

      - name: Comment Terraform Plan on PR
        uses: blinqas/tf-plan-pr-comment@v1
        with:
          output_file: 'tfplan'
          headline: "### Terraform Plan"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}