name: Terraform Plan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'

jobs:
  plan-terraform:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      
      - name: Initialize Terraform
        run: terraform init
      
      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: terraform
          variables: |
            vercel_api_token = "${{secrets.VERCEL_TERRAFORM_API_TOKEN}}"
            vercel_protected_deployment_password = "${{secrets.VERCEL_PROTECTED_DEPLOYMENT_PASSWORD}}"
            github_repository_name = "${{github.event.repository.name}}"